#!/usr/bin/env bash
source "$(dirname "$0")/../utils.sh"

echo "🪟 Installing i3 and related packages..."

install_package i3 i3status xbacklight pavucontrol pulseaudio-utils

echo "✅ i3 installed."

# Copy i3 and i3status configs
clean_and_copy "$DEV_ENV/config-files/.config/i3" "$HOME/.config/i3"
clean_and_copy "$DEV_ENV/config-files/.config/i3status" "$HOME/.config/i3status"

echo "✅ i3 configuration applied."

