#!/usr/bin/env bash

GREEN="\033[0;32m"
RESET="\033[0m"

echo -e "${GREEN}======= Installing i3 Window Manager =======${RESET}"

sudo apt install -y i3 i3status xbacklight pavucontrol pulseaudio-utils rofi

echo -e "${GREEN}======= i3 and Rofi Installed =======${RESET}"

