#!/usr/bin/env bash
source "$(dirname "$0")/../utils.sh"

echo "🚀 Installing Neovim (from GitHub release)..."

# Install build dependencies
install_package curl tar gcc make unzip gettext libtool libtool-bin autoconf automake cmake pkg-config

# Define version and download
version="v0.10.0"
curl -LO "https://github.com/neovim/neovim/releases/download/${version}/nvim-linux64.tar.gz"
tar xzf nvim-linux64.tar.gz

# Remove old and install new
sudo rm -rf /opt/nvim
sudo mv nvim-linux64 /opt/nvim
sudo ln -sf /opt/nvim/bin/nvim /usr/local/bin/nvim
rm nvim-linux64.tar.gz

echo "✅ Neovim installed."

# Sync Neovim config
clean_and_copy "$DEV_ENV/config-files/.config/nvim" "$HOME/.config/nvim"

