#!/usr/bin/env bash
source "$(dirname "$0")/../utils.sh"

log_step "Installing Terminator"
install_package terminator

log_step "Copying Terminator config"
mkdir -p "$HOME/.config/terminator"
clean_and_copy "$DEV_ENV/config-files/terminator_config" "$HOME/.config/terminator/config"

log_step "Installing tree.sh helper script"
sudo cp "$DEV_ENV/config-files/tree.sh" /usr/local/bin/tree.sh
sudo chmod +x /usr/local/bin/tree.sh

